plugins {
  id 'java'
  id 'org.springframework.boot' version '4.1.0'
  id 'io.spring.dependency-management' version '1.1.7'
  id 'org.openapi.generator' version '7.17.0'
}

group = 'com.aestallon'
version = '0.0.1-SNAPSHOT'
description = 'dunadev-backend'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-liquibase'
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-webmvc'
  implementation 'org.springframework.boot:spring-boot-starter-mail'

  implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
  runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
  runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

  implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
  implementation 'io.swagger.core.v3:swagger-annotations:2.2.41'

  implementation 'org.apache.commons:commons-csv:1.14.1'

  compileOnly 'org.projectlombok:lombok'
  developmentOnly 'org.springframework.boot:spring-boot-devtools'
  developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
  runtimeOnly 'org.postgresql:postgresql'
  annotationProcessor 'org.projectlombok:lombok'
  annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
  testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
  testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
  testImplementation 'org.springframework.boot:spring-boot-testcontainers'
  testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
  testImplementation 'org.testcontainers:testcontainers-postgresql'
  testCompileOnly 'org.projectlombok:lombok'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testAnnotationProcessor 'org.projectlombok:lombok'
}

springBoot {
  buildInfo()
}

tasks.named('test') {
  useJUnitPlatform()
}

// this only disables the plain jar creation, not the executable bootJar
// see: https://docs.spring.io/spring-boot/gradle-plugin/packaging.html#packaging-executable.and-plain-archives
tasks.named('jar') {
  enabled = false
}

openApiGenerate {
  generatorName = "spring"
  inputSpec = "$rootDir/spec/dunadev-api.yaml".toString()
  outputDir = "$rootDir/dunadev-backend".toString()
  apiPackage = "com.aestallon.dunadev.rest.api"
  modelPackage = "com.aestallon.dunadev.rest.model"
  configOptions = [
    delegatePattern        : "true",
    fullJavaUtil           : "true",
    library                : "spring-boot",
    openApiNullable        : "false",
    useOptional            : "false",
    useSwaggerUI           : "true",
    hideGenerationTimestamp: "true",
    useSpringBoot3         : "true",
    useTags                : "true",
  ]
  globalProperties = [
    apis  : "",
    models: "",
    supportingFiles: 'ApiUtil.java'
  ]
}
