spring.application.name=dunadev-backend
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.servlet.multipart.max-file-size=10MB
logging.level.org.springframework.web=DEBUG
spring.web.resources.static-locations=classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${dunadev.media-storage-root}/

dunadev.jwt.secret=dev-only-secret-key-that-is-at-least-32-bytes-long
dunadev.jwt.access-token-expiration-minutes=15
dunadev.jwt.refresh-token-expiration-days=7

dunadev.admin-email=admin@dunadev.hu

dunadev.media-storage-root=./media

dunadev.event-critical-days=7
