export * from './account.service';
import { AccountService } from './account.service';
export * from './administration.service';
import { AdministrationService } from './administration.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './organiserEvents.service';
import { OrganiserEventsService } from './organiserEvents.service';
export * from './organiserProfile.service';
import { OrganiserProfileService } from './organiserProfile.service';
export * from './publicEvents.service';
import { PublicEventsService } from './publicEvents.service';
export const APIS = [AccountService, AdministrationService, AuthenticationService, LocationsService, OrganiserEventsService, OrganiserProfileService, PublicEventsService];
