/**
 * DunaDev API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminOrganiserCreateRequest { 
    /**
     * Name of the organisation.
     */
    name: string;
    /**
     * Email address for the primary user of the organisation.
     */
    email: string;
}

