/**
 * DunaDev API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponse { 
    accessToken: string;
    refreshToken: string;
    /**
     * Access token lifetime in seconds.
     */
    expiresIn: number;
    role: string;
}

