/**
 * DunaDev API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventLinkRequest } from './eventLinkRequest';


/**
 * Fields that may be edited on a future event. Date, time, and location are immutable.
 */
export interface EventUpdateRequest { 
    title: string;
    description?: string | null;
    eventUrl?: string | null;
    free: boolean;
    registrationRequired: boolean;
    registrationUrl?: string | null;
    visibleFrom?: string | null;
    links?: Array<EventLinkRequest>;
}

