/**
 * DunaDev API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganiserSummary } from './organiserSummary';
import { LocationSummary } from './locationSummary';
import { EventStatus } from './eventStatus';
import { EventLink } from './eventLink';


/**
 * Public-facing summary of an event, including organiser and location info.
 */
export interface EventSummary { 
    id: number;
    title: string;
    description?: string | null;
    /**
     * Link to the external event page.
     */
    eventUrl?: string | null;
    startsAt: string;
    endsAt?: string | null;
    free: boolean;
    registrationRequired: boolean;
    registrationUrl?: string | null;
    status: EventStatus;
    organiser: OrganiserSummary;
    location?: LocationSummary;
    /**
     * Relative URL of the event\'s cover image, served as a static resource.
     */
    coverImageUrl?: string | null;
    links?: Array<EventLink>;
}



