/**
 * DunaDev API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Minimal organiser info embedded in event responses.
 */
export interface OrganiserSummary { 
    id: number;
    name: string;
    logoUrl?: string | null;
    websiteUrl?: string | null;
}

