/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.ApiError;
import com.aestallon.dunadev.rest.model.PasswordChangeRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Account", description = "Self-service account management for all authenticated users.")
public interface AccountApi {

    default AccountApiDelegate getDelegate() {
        return new AccountApiDelegate() {};
    }

    String PATH_CHANGE_PASSWORD = "/api/me/password";
    /**
     * POST /api/me/password : Change the authenticated user&#39;s password
     * Verifies the current password then replaces it with the new one. Triggers a notification email to the account&#39;s registered address. 
     *
     * @param passwordChangeRequest  (required)
     * @return Password changed successfully. (status code 204)
     *         or Current password is incorrect or new password fails validation. (status code 400)
     *         or Not authenticated. (status code 401)
     */
    @Operation(
        operationId = "changePassword",
        summary = "Change the authenticated user's password",
        description = "Verifies the current password then replaces it with the new one. Triggers a notification email to the account's registered address. ",
        tags = { "Account" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Password changed successfully."),
            @ApiResponse(responseCode = "400", description = "Current password is incorrect or new password fails validation.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AccountApi.PATH_CHANGE_PASSWORD,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> changePassword(
        @Parameter(name = "PasswordChangeRequest", description = "", required = true) @Valid @RequestBody PasswordChangeRequest passwordChangeRequest
    ) {
        return getDelegate().changePassword(passwordChangeRequest);
    }

}
