/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.AdminOrganiserCreateRequest;
import com.aestallon.dunadev.rest.model.AdminOrganiserSummary;
import com.aestallon.dunadev.rest.model.ApiError;
import com.aestallon.dunadev.rest.model.EventSummary;
import com.aestallon.dunadev.rest.model.EventUpdateRequest;
import com.aestallon.dunadev.rest.model.LocationRequest;
import com.aestallon.dunadev.rest.model.LocationSummary;
import org.springframework.lang.Nullable;
import com.aestallon.dunadev.rest.model.OrganiserProfile;
import com.aestallon.dunadev.rest.model.OrganiserUpdateRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Administration", description = "Admin-only management endpoints (ROLE_ADMIN required).")
public interface AdministrationApi {

    default AdministrationApiDelegate getDelegate() {
        return new AdministrationApiDelegate() {};
    }

    String PATH_CREATE_ADMIN_ORGANISER = "/api/admin/organisers";
    /**
     * POST /api/admin/organisers : Invite a new organiser
     * Creates a new organisation and its primary user account. A randomly generated password is emailed to the provided address. The organiser&#39;s status is set to INVITED until their first login, after which it becomes ACTIVE. 
     *
     * @param adminOrganiserCreateRequest  (required)
     * @return Organiser created and invitation email sent. (status code 201)
     *         or Email address is already registered. (status code 409)
     *         or Not an administrator. (status code 403)
     */
    @Operation(
        operationId = "createAdminOrganiser",
        summary = "Invite a new organiser",
        description = "Creates a new organisation and its primary user account. A randomly generated password is emailed to the provided address. The organiser's status is set to INVITED until their first login, after which it becomes ACTIVE. ",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Organiser created and invitation email sent.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AdminOrganiserSummary.class))
            }),
            @ApiResponse(responseCode = "409", description = "Email address is already registered.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdministrationApi.PATH_CREATE_ADMIN_ORGANISER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AdminOrganiserSummary> createAdminOrganiser(
        @Parameter(name = "AdminOrganiserCreateRequest", description = "", required = true) @Valid @RequestBody AdminOrganiserCreateRequest adminOrganiserCreateRequest
    ) {
        return getDelegate().createAdminOrganiser(adminOrganiserCreateRequest);
    }


    String PATH_GET_ADMIN_EVENT = "/api/admin/events/{id}";
    /**
     * GET /api/admin/events/{id} : Get any event by ID
     *
     * @param id  (required)
     * @return The event. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Event not found. (status code 404)
     */
    @Operation(
        operationId = "getAdminEvent",
        summary = "Get any event by ID",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The event.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Event not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdministrationApi.PATH_GET_ADMIN_EVENT,
        produces = { "application/json" }
    )
    default ResponseEntity<EventSummary> getAdminEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().getAdminEvent(id);
    }


    String PATH_GET_ADMIN_ORGANISER = "/api/admin/organisers/{id}";
    /**
     * GET /api/admin/organisers/{id} : Get a single organiser&#39;s profile
     *
     * @param id  (required)
     * @return The organiser&#39;s profile. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Organiser not found. (status code 404)
     */
    @Operation(
        operationId = "getAdminOrganiser",
        summary = "Get a single organiser's profile",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The organiser's profile.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganiserProfile.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Organiser not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdministrationApi.PATH_GET_ADMIN_ORGANISER,
        produces = { "application/json" }
    )
    default ResponseEntity<OrganiserProfile> getAdminOrganiser(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().getAdminOrganiser(id);
    }


    String PATH_GET_ADMIN_ORGANISER_EVENTS = "/api/admin/organisers/{id}/events";
    /**
     * GET /api/admin/organisers/{id}/events : Get all events for a specific organiser
     *
     * @param id  (required)
     * @return The organiser&#39;s events, ordered by start time descending. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Organiser not found. (status code 404)
     */
    @Operation(
        operationId = "getAdminOrganiserEvents",
        summary = "Get all events for a specific organiser",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The organiser's events, ordered by start time descending.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventSummary.class)))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Organiser not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdministrationApi.PATH_GET_ADMIN_ORGANISER_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventSummary>> getAdminOrganiserEvents(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().getAdminOrganiserEvents(id);
    }


    String PATH_GET_ADMIN_ORGANISER_LOCATIONS = "/api/admin/organisers/{id}/locations";
    /**
     * GET /api/admin/organisers/{id}/locations : Get all active locations for a specific organiser
     *
     * @param id  (required)
     * @return The organiser&#39;s active locations. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Organiser not found. (status code 404)
     */
    @Operation(
        operationId = "getAdminOrganiserLocations",
        summary = "Get all active locations for a specific organiser",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The organiser's active locations.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LocationSummary.class)))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Organiser not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdministrationApi.PATH_GET_ADMIN_ORGANISER_LOCATIONS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<LocationSummary>> getAdminOrganiserLocations(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().getAdminOrganiserLocations(id);
    }


    String PATH_GET_ADMIN_UPCOMING_EVENTS = "/api/admin/events/upcoming";
    /**
     * GET /api/admin/events/upcoming : List upcoming events across all organisers
     *
     * @param days  (optional, default to 14)
     * @return Upcoming events within the specified number of days, ordered by start time ascending. (status code 200)
     *         or Not an administrator. (status code 403)
     */
    @Operation(
        operationId = "getAdminUpcomingEvents",
        summary = "List upcoming events across all organisers",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Upcoming events within the specified number of days, ordered by start time ascending.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventSummary.class)))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdministrationApi.PATH_GET_ADMIN_UPCOMING_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventSummary>> getAdminUpcomingEvents(
        @Min(value = 1) @Max(value = 60) @Parameter(name = "days", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "days", required = false, defaultValue = "14") Integer days
    ) {
        return getDelegate().getAdminUpcomingEvents(days);
    }


    String PATH_LIST_ADMIN_ORGANISERS = "/api/admin/organisers";
    /**
     * GET /api/admin/organisers : List all organisers
     *
     * @return All organisers with event and location counts. (status code 200)
     *         or Not an administrator. (status code 403)
     */
    @Operation(
        operationId = "listAdminOrganisers",
        summary = "List all organisers",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "All organisers with event and location counts.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = AdminOrganiserSummary.class)))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AdministrationApi.PATH_LIST_ADMIN_ORGANISERS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<AdminOrganiserSummary>> listAdminOrganisers(
        
    ) {
        return getDelegate().listAdminOrganisers();
    }


    String PATH_UPDATE_ADMIN_EVENT = "/api/admin/events/{id}";
    /**
     * PUT /api/admin/events/{id} : Update any event&#39;s editable fields
     *
     * @param id  (required)
     * @param eventUpdateRequest  (required)
     * @return Event updated. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Event not found. (status code 404)
     */
    @Operation(
        operationId = "updateAdminEvent",
        summary = "Update any event's editable fields",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Event updated.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Event not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AdministrationApi.PATH_UPDATE_ADMIN_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EventSummary> updateAdminEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "EventUpdateRequest", description = "", required = true) @Valid @RequestBody EventUpdateRequest eventUpdateRequest
    ) {
        return getDelegate().updateAdminEvent(id, eventUpdateRequest);
    }


    String PATH_UPDATE_ADMIN_LOCATION = "/api/admin/locations/{id}";
    /**
     * PUT /api/admin/locations/{id} : Update any location
     *
     * @param id  (required)
     * @param locationRequest  (required)
     * @return Location updated. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Location not found. (status code 404)
     */
    @Operation(
        operationId = "updateAdminLocation",
        summary = "Update any location",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Location updated.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LocationSummary.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Location not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AdministrationApi.PATH_UPDATE_ADMIN_LOCATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<LocationSummary> updateAdminLocation(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "LocationRequest", description = "", required = true) @Valid @RequestBody LocationRequest locationRequest
    ) {
        return getDelegate().updateAdminLocation(id, locationRequest);
    }


    String PATH_UPDATE_ADMIN_ORGANISER = "/api/admin/organisers/{id}";
    /**
     * PUT /api/admin/organisers/{id} : Update any organiser&#39;s profile
     *
     * @param id  (required)
     * @param organiserUpdateRequest  (required)
     * @return Profile updated. (status code 200)
     *         or Not an administrator. (status code 403)
     *         or Organiser not found. (status code 404)
     */
    @Operation(
        operationId = "updateAdminOrganiser",
        summary = "Update any organiser's profile",
        tags = { "Administration" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile updated.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganiserProfile.class))
            }),
            @ApiResponse(responseCode = "403", description = "Not an administrator."),
            @ApiResponse(responseCode = "404", description = "Organiser not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AdministrationApi.PATH_UPDATE_ADMIN_ORGANISER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<OrganiserProfile> updateAdminOrganiser(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "OrganiserUpdateRequest", description = "", required = true) @Valid @RequestBody OrganiserUpdateRequest organiserUpdateRequest
    ) {
        return getDelegate().updateAdminOrganiser(id, organiserUpdateRequest);
    }

}
