/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.AuthResponse;
import com.aestallon.dunadev.rest.model.LoginRequest;
import com.aestallon.dunadev.rest.model.RefreshRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Authentication", description = "Login and token refresh endpoints.")
public interface AuthenticationApi {

    default AuthenticationApiDelegate getDelegate() {
        return new AuthenticationApiDelegate() {};
    }

    String PATH_LOGIN = "/api/auth/login";
    /**
     * POST /api/auth/login : Authenticate with email and password
     * Validates the provided credentials and returns an access/refresh token pair. 
     *
     * @param loginRequest  (required)
     * @return Authentication successful. (status code 200)
     *         or Invalid credentials. (status code 401)
     */
    @Operation(
        operationId = "login",
        summary = "Authenticate with email and password",
        description = "Validates the provided credentials and returns an access/refresh token pair. ",
        tags = { "Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Authentication successful.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid credentials.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthenticationApi.PATH_LOGIN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthResponse> login(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    ) {
        return getDelegate().login(loginRequest);
    }


    String PATH_REFRESH_TOKEN = "/api/auth/refresh";
    /**
     * POST /api/auth/refresh : Refresh an access token
     * Accepts a valid refresh token and returns a new access/refresh token pair. 
     *
     * @param refreshRequest  (required)
     * @return Token refreshed successfully. (status code 200)
     *         or Invalid or expired refresh token. (status code 401)
     */
    @Operation(
        operationId = "refreshToken",
        summary = "Refresh an access token",
        description = "Accepts a valid refresh token and returns a new access/refresh token pair. ",
        tags = { "Authentication" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Token refreshed successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "Invalid or expired refresh token.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthenticationApi.PATH_REFRESH_TOKEN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthResponse> refreshToken(
        @Parameter(name = "RefreshRequest", description = "", required = true) @Valid @RequestBody RefreshRequest refreshRequest
    ) {
        return getDelegate().refreshToken(refreshRequest);
    }

}
