/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.LocationRequest;
import com.aestallon.dunadev.rest.model.LocationSummary;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Locations", description = "Location management for organisers (authentication required).")
public interface LocationsApi {

    default LocationsApiDelegate getDelegate() {
        return new LocationsApiDelegate() {};
    }

    String PATH_CREATE_LOCATION = "/api/locations";
    /**
     * POST /api/locations : Create a new location
     *
     * @param locationRequest  (required)
     * @return Location created successfully. (status code 200)
     *         or Not authenticated. (status code 401)
     */
    @Operation(
        operationId = "createLocation",
        summary = "Create a new location",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Location created successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LocationSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = LocationsApi.PATH_CREATE_LOCATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<LocationSummary> createLocation(
        @Parameter(name = "LocationRequest", description = "", required = true) @Valid @RequestBody LocationRequest locationRequest
    ) {
        return getDelegate().createLocation(locationRequest);
    }


    String PATH_DELETE_LOCATION = "/api/locations/{id}";
    /**
     * DELETE /api/locations/{id} : Delete a location (soft-delete if used by events)
     *
     * @param id  (required)
     * @return Location deleted successfully. (status code 204)
     *         or Not authenticated. (status code 401)
     *         or Location not found or not owned by the authenticated user. (status code 404)
     */
    @Operation(
        operationId = "deleteLocation",
        summary = "Delete a location (soft-delete if used by events)",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Location deleted successfully."),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Location not found or not owned by the authenticated user.")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = LocationsApi.PATH_DELETE_LOCATION
    )
    default ResponseEntity<Void> deleteLocation(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().deleteLocation(id);
    }


    String PATH_GET_LOCATION = "/api/locations/{id}";
    /**
     * GET /api/locations/{id} : Get a single location by ID
     *
     * @param id  (required)
     * @return The requested location. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Location not found or not owned by the authenticated user. (status code 404)
     */
    @Operation(
        operationId = "getLocation",
        summary = "Get a single location by ID",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The requested location.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LocationSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Location not found or not owned by the authenticated user.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LocationsApi.PATH_GET_LOCATION,
        produces = { "application/json" }
    )
    default ResponseEntity<LocationSummary> getLocation(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().getLocation(id);
    }


    String PATH_GET_MY_LOCATIONS = "/api/locations";
    /**
     * GET /api/locations : List the logged-in organiser&#39;s active locations
     *
     * @return A list of the organiser&#39;s active locations. (status code 200)
     *         or Not authenticated. (status code 401)
     */
    @Operation(
        operationId = "getMyLocations",
        summary = "List the logged-in organiser's active locations",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of the organiser's active locations.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LocationSummary.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = LocationsApi.PATH_GET_MY_LOCATIONS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<LocationSummary>> getMyLocations(
        
    ) {
        return getDelegate().getMyLocations();
    }


    String PATH_UPDATE_LOCATION = "/api/locations/{id}";
    /**
     * PUT /api/locations/{id} : Update an existing location
     *
     * @param id  (required)
     * @param locationRequest  (required)
     * @return Location updated successfully. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Location not found or not owned by the authenticated user. (status code 404)
     */
    @Operation(
        operationId = "updateLocation",
        summary = "Update an existing location",
        tags = { "Locations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Location updated successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = LocationSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Location not found or not owned by the authenticated user.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = LocationsApi.PATH_UPDATE_LOCATION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<LocationSummary> updateLocation(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "LocationRequest", description = "", required = true) @Valid @RequestBody LocationRequest locationRequest
    ) {
        return getDelegate().updateLocation(id, locationRequest);
    }

}
