/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.EventRequest;
import com.aestallon.dunadev.rest.model.EventSummary;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Organiser Events", description = "Event management for authenticated organisers.")
public interface OrganiserEventsApi {

    default OrganiserEventsApiDelegate getDelegate() {
        return new OrganiserEventsApiDelegate() {};
    }

    String PATH_CREATE_EVENT = "/api/events";
    /**
     * POST /api/events : Create a new event
     *
     * @param eventRequest  (required)
     * @return Event created successfully. (status code 201)
     *         or Not authenticated. (status code 401)
     *         or Location not found or not owned by the authenticated organiser. (status code 404)
     */
    @Operation(
        operationId = "createEvent",
        summary = "Create a new event",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Event created successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Location not found or not owned by the authenticated organiser.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrganiserEventsApi.PATH_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EventSummary> createEvent(
        @Parameter(name = "EventRequest", description = "", required = true) @Valid @RequestBody EventRequest eventRequest
    ) {
        return getDelegate().createEvent(eventRequest);
    }


    String PATH_GET_MY_EVENTS = "/api/events/my";
    /**
     * GET /api/events/my : List the authenticated organiser&#39;s events
     * Returns all events created by the authenticated organiser, ordered by start time descending (most recent first). 
     *
     * @return The organiser&#39;s events (past and upcoming). (status code 200)
     *         or Not authenticated. (status code 401)
     */
    @Operation(
        operationId = "getMyEvents",
        summary = "List the authenticated organiser's events",
        description = "Returns all events created by the authenticated organiser, ordered by start time descending (most recent first). ",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The organiser's events (past and upcoming).", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventSummary.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = OrganiserEventsApi.PATH_GET_MY_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventSummary>> getMyEvents(
        
    ) {
        return getDelegate().getMyEvents();
    }

}
