/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.EventRelocateRequest;
import com.aestallon.dunadev.rest.model.EventRequest;
import com.aestallon.dunadev.rest.model.EventRescheduleRequest;
import com.aestallon.dunadev.rest.model.EventSummary;
import com.aestallon.dunadev.rest.model.EventUpdateRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Organiser Events", description = "Event management for authenticated organisers.")
public interface OrganiserEventsApi {

    default OrganiserEventsApiDelegate getDelegate() {
        return new OrganiserEventsApiDelegate() {};
    }

    String PATH_CANCEL_EVENT = "/api/events/{id}/cancel";
    /**
     * POST /api/events/{id}/cancel : Cancel an event
     *
     * @param id  (required)
     * @return Event cancelled or deleted. (status code 204)
     *         or Not authenticated. (status code 401)
     *         or Event not found or not owned by the authenticated organiser. (status code 404)
     *         or Event has already started or is in an unalterable state. (status code 409)
     */
    @Operation(
        operationId = "cancelEvent",
        summary = "Cancel an event",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Event cancelled or deleted."),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Event not found or not owned by the authenticated organiser."),
            @ApiResponse(responseCode = "409", description = "Event has already started or is in an unalterable state.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrganiserEventsApi.PATH_CANCEL_EVENT
    )
    default ResponseEntity<Void> cancelEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().cancelEvent(id);
    }


    String PATH_CREATE_EVENT = "/api/events";
    /**
     * POST /api/events : Create a new event
     *
     * @param eventRequest  (required)
     * @return Event created successfully. (status code 201)
     *         or Not authenticated. (status code 401)
     *         or Location not found or not owned by the authenticated organiser. (status code 404)
     */
    @Operation(
        operationId = "createEvent",
        summary = "Create a new event",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Event created successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Location not found or not owned by the authenticated organiser.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrganiserEventsApi.PATH_CREATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EventSummary> createEvent(
        @Parameter(name = "EventRequest", description = "", required = true) @Valid @RequestBody EventRequest eventRequest
    ) {
        return getDelegate().createEvent(eventRequest);
    }


    String PATH_GET_EVENT = "/api/events/{id}";
    /**
     * GET /api/events/{id} : Get a single event owned by the authenticated organiser
     *
     * @param id  (required)
     * @return The requested event. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Event not found or not owned by the authenticated organiser. (status code 404)
     */
    @Operation(
        operationId = "getEvent",
        summary = "Get a single event owned by the authenticated organiser",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The requested event.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Event not found or not owned by the authenticated organiser.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = OrganiserEventsApi.PATH_GET_EVENT,
        produces = { "application/json" }
    )
    default ResponseEntity<EventSummary> getEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return getDelegate().getEvent(id);
    }


    String PATH_GET_MY_EVENTS = "/api/events/my";
    /**
     * GET /api/events/my : List the authenticated organiser&#39;s events
     * Returns all events created by the authenticated organiser, ordered by start time descending (most recent first). 
     *
     * @return The organiser&#39;s events (past and upcoming). (status code 200)
     *         or Not authenticated. (status code 401)
     */
    @Operation(
        operationId = "getMyEvents",
        summary = "List the authenticated organiser's events",
        description = "Returns all events created by the authenticated organiser, ordered by start time descending (most recent first). ",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The organiser's events (past and upcoming).", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventSummary.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = OrganiserEventsApi.PATH_GET_MY_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventSummary>> getMyEvents(
        
    ) {
        return getDelegate().getMyEvents();
    }


    String PATH_RELOCATE_EVENT = "/api/events/{id}/relocate";
    /**
     * POST /api/events/{id}/relocate : Change the location of an event
     *
     * @param id  (required)
     * @param eventRelocateRequest  (required)
     * @return Updated event summary. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Event not found or not owned by the authenticated organiser. (status code 404)
     *         or Event has already started or is cancelled. (status code 409)
     */
    @Operation(
        operationId = "relocateEvent",
        summary = "Change the location of an event",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated event summary.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Event not found or not owned by the authenticated organiser."),
            @ApiResponse(responseCode = "409", description = "Event has already started or is cancelled.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrganiserEventsApi.PATH_RELOCATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EventSummary> relocateEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "EventRelocateRequest", description = "", required = true) @Valid @RequestBody EventRelocateRequest eventRelocateRequest
    ) {
        return getDelegate().relocateEvent(id, eventRelocateRequest);
    }


    String PATH_RESCHEDULE_EVENT = "/api/events/{id}/reschedule";
    /**
     * POST /api/events/{id}/reschedule : Reschedule an event
     *
     * @param id  (required)
     * @param eventRescheduleRequest  (required)
     * @return Updated event summary. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Event not found or not owned by the authenticated organiser. (status code 404)
     *         or Event has already started or is cancelled. (status code 409)
     */
    @Operation(
        operationId = "rescheduleEvent",
        summary = "Reschedule an event",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated event summary.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Event not found or not owned by the authenticated organiser."),
            @ApiResponse(responseCode = "409", description = "Event has already started or is cancelled.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrganiserEventsApi.PATH_RESCHEDULE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EventSummary> rescheduleEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "EventRescheduleRequest", description = "", required = true) @Valid @RequestBody EventRescheduleRequest eventRescheduleRequest
    ) {
        return getDelegate().rescheduleEvent(id, eventRescheduleRequest);
    }


    String PATH_UPDATE_EVENT = "/api/events/{id}";
    /**
     * PUT /api/events/{id} : Update the editable fields of an upcoming event
     * Updates title, description, links, and other metadata of a future event. Date, time, and location cannot be changed through this endpoint. 
     *
     * @param id  (required)
     * @param eventUpdateRequest  (required)
     * @return Event updated successfully. (status code 200)
     *         or The event has already started or passed. (status code 400)
     *         or Not authenticated. (status code 401)
     *         or Event not found or not owned by the authenticated organiser. (status code 404)
     */
    @Operation(
        operationId = "updateEvent",
        summary = "Update the editable fields of an upcoming event",
        description = "Updates title, description, links, and other metadata of a future event. Date, time, and location cannot be changed through this endpoint. ",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Event updated successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "400", description = "The event has already started or passed."),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Event not found or not owned by the authenticated organiser.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = OrganiserEventsApi.PATH_UPDATE_EVENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<EventSummary> updateEvent(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "EventUpdateRequest", description = "", required = true) @Valid @RequestBody EventUpdateRequest eventUpdateRequest
    ) {
        return getDelegate().updateEvent(id, eventUpdateRequest);
    }


    String PATH_UPLOAD_EVENT_IMAGE = "/api/events/{id}/image";
    /**
     * POST /api/events/{id}/image : Upload or replace the cover image of an event
     *
     * @param id  (required)
     * @param file  (required)
     * @return Image stored successfully. Returns the updated event summary. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Event not found or not owned by the authenticated organiser. (status code 404)
     */
    @Operation(
        operationId = "uploadEventImage",
        summary = "Upload or replace the cover image of an event",
        tags = { "Organiser Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Image stored successfully. Returns the updated event summary.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventSummary.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Event not found or not owned by the authenticated organiser.")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrganiserEventsApi.PATH_UPLOAD_EVENT_IMAGE,
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<EventSummary> uploadEventImage(
        @NotNull @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "file", description = "", required = true) @RequestPart(value = "file", required = true) MultipartFile file
    ) {
        return getDelegate().uploadEventImage(id, file);
    }

}
