/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.OrganiserProfile;
import com.aestallon.dunadev.rest.model.OrganiserUpdateRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Organiser Profile", description = "Organiser profile management (authentication required).")
public interface OrganiserProfileApi {

    default OrganiserProfileApiDelegate getDelegate() {
        return new OrganiserProfileApiDelegate() {};
    }

    String PATH_GET_MY_ORGANISER_PROFILE = "/api/organiser/me";
    /**
     * GET /api/organiser/me : Get the authenticated organiser&#39;s profile
     *
     * @return The organiser&#39;s profile. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Organiser profile not found. (status code 404)
     */
    @Operation(
        operationId = "getMyOrganiserProfile",
        summary = "Get the authenticated organiser's profile",
        tags = { "Organiser Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The organiser's profile.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganiserProfile.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Organiser profile not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = OrganiserProfileApi.PATH_GET_MY_ORGANISER_PROFILE,
        produces = { "application/json" }
    )
    default ResponseEntity<OrganiserProfile> getMyOrganiserProfile(
        
    ) {
        return getDelegate().getMyOrganiserProfile();
    }


    String PATH_UPDATE_MY_ORGANISER_PROFILE = "/api/organiser/me";
    /**
     * PUT /api/organiser/me : Update the authenticated organiser&#39;s profile
     *
     * @param organiserUpdateRequest  (required)
     * @return Profile updated successfully. (status code 200)
     *         or Not authenticated. (status code 401)
     *         or Organiser profile not found. (status code 404)
     */
    @Operation(
        operationId = "updateMyOrganiserProfile",
        summary = "Update the authenticated organiser's profile",
        tags = { "Organiser Profile" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Profile updated successfully.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrganiserProfile.class))
            }),
            @ApiResponse(responseCode = "401", description = "Not authenticated."),
            @ApiResponse(responseCode = "404", description = "Organiser profile not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = OrganiserProfileApi.PATH_UPDATE_MY_ORGANISER_PROFILE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<OrganiserProfile> updateMyOrganiserProfile(
        @Parameter(name = "OrganiserUpdateRequest", description = "", required = true) @Valid @RequestBody OrganiserUpdateRequest organiserUpdateRequest
    ) {
        return getDelegate().updateMyOrganiserProfile(organiserUpdateRequest);
    }

}
