/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.aestallon.dunadev.rest.api;

import com.aestallon.dunadev.rest.model.EventSummary;
import org.springframework.lang.Nullable;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.17.0")
@Validated
@Tag(name = "Public Events", description = "Publicly accessible event endpoints (no authentication required).")
public interface PublicEventsApi {

    default PublicEventsApiDelegate getDelegate() {
        return new PublicEventsApiDelegate() {};
    }

    String PATH_GET_EVENTS_BY_MONTH = "/api/events";
    /**
     * GET /api/events : List events for a given month
     * Returns all publicly visible, non-cancelled events whose start time falls within the specified year and month. Intended for the monthly event list and calendar view on the landing page. 
     *
     * @param year Four-digit year. (required)
     * @param month Month number (1–12). (required)
     * @return A list of events for the requested month ordered by start time ascending. (status code 200)
     *         or Invalid year or month parameter. (status code 400)
     */
    @Operation(
        operationId = "getEventsByMonth",
        summary = "List events for a given month",
        description = "Returns all publicly visible, non-cancelled events whose start time falls within the specified year and month. Intended for the monthly event list and calendar view on the landing page. ",
        tags = { "Public Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of events for the requested month ordered by start time ascending.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventSummary.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid year or month parameter.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PublicEventsApi.PATH_GET_EVENTS_BY_MONTH,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventSummary>> getEventsByMonth(
        @NotNull @Parameter(name = "year", description = "Four-digit year.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "year", required = true) Integer year,
        @NotNull @Min(value = 1) @Max(value = 12) @Parameter(name = "month", description = "Month number (1–12).", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "month", required = true) Integer month
    ) {
        return getDelegate().getEventsByMonth(year, month);
    }


    String PATH_GET_UPCOMING_EVENTS = "/api/events/upcoming";
    /**
     * GET /api/events/upcoming : List the next upcoming events
     * Returns the closest upcoming events that are publicly visible and not cancelled. Intended for the landing-page hero cards. 
     *
     * @param limit Maximum number of events to return (1–20). (optional, default to 5)
     * @return A list of upcoming events ordered by start time ascending. (status code 200)
     */
    @Operation(
        operationId = "getUpcomingEvents",
        summary = "List the next upcoming events",
        description = "Returns the closest upcoming events that are publicly visible and not cancelled. Intended for the landing-page hero cards. ",
        tags = { "Public Events" },
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of upcoming events ordered by start time ascending.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = EventSummary.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = PublicEventsApi.PATH_GET_UPCOMING_EVENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<EventSummary>> getUpcomingEvents(
        @Min(value = 1) @Max(value = 20) @Parameter(name = "limit", description = "Maximum number of events to return (1–20).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "5") Integer limit
    ) {
        return getDelegate().getUpcomingEvents(limit);
    }

}
